### ISSUE TITLE
bad parameter naming in captcha.render_captcha in templates

### ISSUE THREAD

**Issue by johndou-and-friends** [alisharify7/flask_captcha2#2]
In captcha.render_captcha filter in templates 
The parameter name in the filter is not good 

It is like a combination of all these names 
 Camel, Snake, Kebab and Case Pascal

Can you modify this and convert all parameters to love case or use one naming method for all?

for example :
this
```python
     model_name= #LowerCase
     class=#LowerCase
     id=#LowerCase
     style=#LowerCase
     dataset= #LowerCase
     ParentFormID= #Bad
     BtnText= #Bad
     event= #LowerCase
     hiddenBadge= #Bad
```

should be like this:
```python
     model_name= 
     class=
     id=
     style=
     dataset= 
     parent_form_id= 
     btn_text= 
     event= 
     hidden_badge= 
```

**Comment by devbarsamco** [comment]
> In captcha.render_captcha filter in templates The parameter name in the filter is not good
> 
> It is like a combination of all these names Camel, Snake, Kebab and Case Pascal
> 
> Can you modify this and convert all parameters to love case or use one naming method for all?
> 
> for example : this
> 
> ```python
>      model_name= #LowerCase
>      class=#LowerCase
>      id=#LowerCase
>      style=#LowerCase
>      dataset= #LowerCase
>      ParentFormID= #Bad
>      BtnText= #Bad
>      event= #LowerCase
>      hiddenBadge= #Bad
> ```
> 
> should be like this:
> 
> ```python
>      model_name= 
>      class=
>      id=
>      style=
>      dataset= 
>      parent_form_id= 
>      btn_text= 
>      event= 
>      hidden_badge= 
> ```

@alisharify7

**Comment by alisharify7** [comment]
> In captcha.render_captcha filter in templates The parameter name in the filter is not good
> 
> It is like a combination of all these names Camel, Snake, Kebab and Case Pascal
> 
> Can you modify this and convert all parameters to love case or use one naming method for all?
> 
> for example : this
> 
> ```python
>      model_name= #LowerCase
>      class=#LowerCase
>      id=#LowerCase
>      style=#LowerCase
>      dataset= #LowerCase
>      ParentFormID= #Bad
>      BtnText= #Bad
>      event= #LowerCase
>      hiddenBadge= #Bad
> ```
> 
> should be like this:
> 
> ```python
>      model_name= 
>      class=
>      id=
>      style=
>      dataset= 
>      parent_form_id= 
>      btn_text= 
>      event= 
>      hidden_badge= 
> ```
hi thanks for reporting this 
that's right.  I'll work on this issue
